wasdk/wasmparser

.gitignore, es6-tsconfig.json, package-lock.json, package.json, src/WasmDis.ts, src/WasmEmitter.ts, src/WasmParserTransform.ts, src/index.ts
Add an output module that uses standard ES modules with proper file extensions.
This bundle is exposed via the "module" attribute in the package.json.
The es6-tsconfig.json overrides only the necessary parts of the base config.
This is a follow-up on #22 `require` can use the file extension at the end in Node. File extensions are required when downstream users use standard ES modules. Verified that tests are still passing and the build output is correct.
CC @ericsl
=> Add ES-module output bundle

src/WasmDis.ts
The JSVM already uses ropes under the hood, so the
LineBuffer class is just unnecessary overhead. In
fact, the Google Earth big .wasm file from the pthread
build disassembles 10% faster with this simplification
in Node 12.
=> Remove LineBuffer to avoid the userland ropes.

src/WasmDis.ts, test.ts
Quick change to produce a truncated output. This may not be worth merging in as it is not our long term solution.
=> Add option to truncate disassembly

src/WasmDis.spec.ts, src/WasmDis.ts
This adds a new DevToolsNameGenerator class (similar to the NameSectionReader), which is responsible for generating the names depending on the name source (import, export, name section). The corresponding DevToolsNameResolver can then be used to resolve the names during disassembling wasm binaries.
The new DevToolsNameGenerator will adhere to the following naming scheme, if no name is set in the name section:
1. For entities (functions, tables, memories, or globals) that are imported, and which have both a <module_name> and a <field_name>, we generate a name in the form $<module_name>.<field_name>.
2. Otherwise, for entities (functions, tables, memories, or globals) that are exported, we take the first entry in the exports table and generate a name $<export_name>.
3. Otherwise:
- Types …
=> Adding DevToolsNameGenerator and DevToolsNameResolver

src/WasmDis.spec.ts, src/WasmDis.ts
In this PR, getResult would return also the code section offsets as an array of 2 elements [beginCodeSectionOffset, endCodeSectionOffset]. From that, we can detect possible breakable line/bytecode offset in WAT.
TODO: in the follow-up PR, we would return an array of array of 2 elements such as
[[beginFunctionBody1Offset, endFunctionBody1Offset], [beginFunctionBody2Offset, endFunctionBody2Offset], ...] to avoid detecting function header as breakable line/offset
=> Log the body function offsets for better detecting possible breakable WAT positions

wabt-compatibility.spec.ts
As mentioned in https://github.com/wasdk/wasmparser/issues/33 and https://bugs.chromium.org/p/chromium/issues/detail?id=1066386, we want to generate WAT that is wabt-compatible.
Some existing ones are not wabt-compatible so we exclude those.
=> Add wabt compatibility test

src/WasmDis.ts, test/atomic.0.wasm.out, test/atomic.1.wasm.out, test/threads.0.wasm.out, wabt-compatibility.spec.ts
According to https://github.com/WebAssembly/threads/pull/74, memory text syntax has changed.
Also, wabt need 'threads' flags to run atomic operators
Bug: https://github.com/wasdk/wasmparser/issues/33
=> [wabt-compatibility] Change memory text syntax

disassemble-wasm.js, examples/disassemble-wasm-1.js, examples/disassemble-wasm-2.js, examples/dump-section.js, examples/print_imports_exports.js, package.json
Drive-by: Run `build` script as part of the `prepare` step.
=> Fix up paths in binaries / examples

src/WasmDis.ts, test/memory_bulk.0.wasm.out, wabt-compatibility.spec.ts
According to https://github.com/WebAssembly/bulk-memory-operations/blob/master/proposals/bulk-memory-operations/Overview.md, instructions as table.init, table.copy has changed.
Bug: https://github.com/wasdk/wasmparser/issues/33
=> [wabt-compatibility] bulk memory

package-lock.json, package.json
This adds support for automatically generating the `CHANGELOG.md`
using the @semantic-release/changelog plugin, and automatically
synchronizing `package.json` et all changes back to GitHub.
This also updates the `version` in the `package.json` to 1.0.0
to synchronize it with npmjs.com
Refs: #52
=> chore: setup CHANGELOG.md automation and git updates

.npmignore
For the source maps that we generate for both the `esm` as well
as the `cjs` target, we need to include the `src/*.ts` files as
well, otherwise the sourcemaps don't work when pulling from npm.
=> chore(package): add files to make source maps work

package.json
This is to ensure that all tools that can deal with ES modules can also deal with the `dist/esm` output (I noticed this because `rollup` started to break with nullish coalescing that I used in `src/WasmDis.ts`).
=> fix: make `dist/esm` output ES2015 compatible

src/WasmParser.ts, test/br.wast.0.wasm.out, test/br_table.wast.0.wasm.out, test/imports.wast.98.wasm.out, test/linking.wast.20.wasm.out, test/malloc.wasm.out, test/memory_trap.wast.0.wasm.out, test/nop.wast.0.wasm.out, test/resizing.wast.0.wasm.out, test/resizing.wast.1.wasm.out, test/resizing.wast.2.wasm.out, test/return.wast.0.wasm.out, test/spec.wasm.out, test/unreachable.wast.0.wasm.out
The operator isn't named `grow_memory` but `memory.grow` in the
latest WebAssembly specification. [^1]
[^1]: https://webassembly.github.io/spec/core/text/instructions.html
=> fix: `grow_memory` -> `memory.grow`

src/WasmParser.ts, test/atomic.1.wasm.out, test/threads.0.wasm.out, wabt-compatibility.spec.ts
Temporarily disable the relevant wabt compatibility fixes until we can
upgrade to the latest wabt.js, which requires more changes.
Refs: WebAssembly/threads#149
=> fix: rename atomic.notify and *.atomic.wait

jest.config.js, package.json, src/WasmParser.ts, test/disassemble-chunk.test.ts
This fixes the outstanding issue that wasm binaries utilizing the bulk memory proposal (in particular the extended elements section entries) cannot be parsed in chunks, and adds randomized tests to make sure we exercise the different chunk sizes properly (and catch bugs).
I just went for `jest-chance` here for the randomization.
Drive-by-fix: Also moved the `jest` configuration into `package.json` as I wasted a good 10 minutes on figuring out why setting `"jest.globalSetup"`in `package.json` doesn't work. 🤦
=> Fix and test chunked disassembly

src/WasmParser.ts, test/WasmDis.test.ts
According to the WebAssembly specification, custom sections shouldn't
cause parsing to fail, and so we shouldn't error out because of an
unsupported subsection in the "name" custom section. This will make
the library more robust wrt. additions of more custom names.
Bug: https://crbug.com/1137335
=> fix: ignore unsupported "name" subsections

src/WasmDis.ts, src/WasmParser.ts, test/WasmDis.test.ts
This adds initial support for extended "name" subsections, including
type, table, memory, and global names. While the proposal is currently
at Stage 1 only, it's already being implemented in Binaryen and thus
in Emscripten as well as wabt, so it makes sense to support this early
on.
As a drive-by-fix, this also removes some of the code duplication that
we had in the `NameSectionNameResolver` and the `DevToolsNameResolver`
classes.
Bug: https://crbug.com/1137335
Proposal: https://github.com/WebAssembly/extended-name-section
=> feat: support some extended name subsections

src/WasmDis.ts
BREAKING CHANGE: the `start` and `end` fields of `IFunctionBodyOffset`
were optional members before.
=> fix: both members of IFunctionBodyOffset are mandatory numbers

src/WasmDis.ts, src/WasmParser.ts, src/index.ts, test/WasmDis.test.ts, test/WasmParser.test.ts
BREAKING CHANGE: IFunctionType is replaced by the more general ITypeEntry.
BREAKING CHANGE: Type is now a class; the former enum is now called TypeKind. Several other interfaces now use Type instances instead of numbers to describe types.
=> feat: add support for WasmGC proposal

src/WasmDis.ts, test/WasmDis.test.ts
Without this fix, standalone disassembly worked, but attempting to disassemble modules with exceptions in DevTools resulted in:
`TypeError: Cannot read property '0' of null`.
=> fix: missing initializer in devtools name generator for exceptions

src/WasmDis.ts, src/WasmParser.ts, test/WasmDis.test.ts
From the "reference types" proposal:
- select_with_type
From the "function references" proposal:
- br_on_non_null
From the latest updates to the GC proposal:
- br_on_cast_fail
- br_on_non_func
- br_on_non_data
- br_on_non_i31
Not yet standardized experiments in V8:
- array.copy
- rtt.fresh_sub
=> feat: implement more instructions

src/WasmDis.ts, test/WasmDis.test.ts
Escapes export name strings [§6.3.3](https://webassembly.github.io/spec/core/bikeshed/#strings) using `JSON.stringify`.
Fixes output like this:
```wasm
(module
(func $___ (;0;) (export ""(;") (result i32)
i32.const 2
)
)
```
Into output like this:
```wasm
(module
(func $___ (;0;) (export "\"(;") (result i32)
i32.const 2
)
)
```
=> Escape export name strings in wat output

src/WasmDis.ts, src/WasmParser.ts, test/WasmDis.test.ts
The "milestone 4" spec currently lives at https://docs.google.com/document/d/1afthjsL_B9UaMqCA5ekgVmOm75BVFu6duHNsN9-gnXw/edit, will soon be merged into https://bit.ly/3cWcm6Q.
The module format is backwards-compatible, so this isn't a breaking change.
=> feat: update GC proposal support to "milestone 4"

.github/workflows/main.yml
Address actions errors when release is happening:
```
build (18.x)
Node.js 12 actions are deprecated. Please update the following actions to use Node.js 16: actions/checkout@v2, actions/setup-node@v2. For more information see: https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/.
release
Node.js 12 actions are deprecated. Please update the following actions to use Node.js 16: actions/checkout@v2, actions/setup-node@v1. For more information see: https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/.
```
=> chore(deps): CI actions update

src/WasmDis.ts, src/WasmParser.ts, test/WasmDis.test.ts
=> feat: sync op and type codes for GC proposal

src/WasmParser.ts
The following instructions were renamed in wasm-gc (https://github.com/WebAssembly/gc/pull/447):
extern.internalize -> any.convert_extern
extern.externalize -> extern.convert_any
=> feat: rename extern.internalize and extern.externalize instructions
